---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dgcxs8dd2koc/public_html/
    # Deploys your main website (Vite build)
    - /bin/cp -R src/frontend/dist/* $DEPLOYPATH
    # Fixes the missing images
    - /bin/cp -R frontend/public/* $DEPLOYPATH
    # Deploys the form handler to the live folder
    - /bin/cp frontend/contact.php $DEPLOYPATH
